### ISSUE TITLE
Add documentation for breaking out of /tmp sandbox

### ISSUE THREAD

**Issue by RyanSquared** [hashbang/admin-tools#51]
If it's possible, adding something in `doc/` would be nice for providing instructions to break out of the `/tmp` sandbox. @daurnimator @KellerFuchs

**Comment by daurnimator** [comment]
I've used `nsenter` to enter a user's mount namespace and access their /tmp.

**Comment by RyanSquared** [comment]
I'll poke around with that later, then, and see if I can get something reproducible from it.

**Comment by KellerFuchs** [comment]
Moreover, if you connect as `root`, `sudo`ing to a user will put you in their namespace, and their `/tmp` can otherwise be found in `/tmp/inst/$user`.

`pam_namespace` has a [known issue](https://github.com/hashbang/shell-etc/issues/74) where it fails to bring you out of the namespace when using, for instance, `sudo`.

**Comment by RyanSquared** [comment]
Closing in favor of hoping `pam_namespace` gets fixed instead.
