### ISSUE TITLE
Document running a command across all (or several) shell servers

### ISSUE THREAD

**Issue by RyanSquared** [hashbang/admin-tools#62]
This is good for stuff like rebooting all servers at once, which should be done right now but honestly I have no idea how to go about it.

**Comment by KellerFuchs** [comment]
`ansible shell_servers -a reboot`.  (Also, only `da1` and `to1` needed the reboop)

I'm not opposed to documenting common commands, but OTOH Ansible documentation is waaaay out of scope.

**Comment by DeviaVir** [comment]
@RyanSquared it might make sense for you to grab a github wiki page and document these things at least for yourself, i.e. `ansible [group] -a [command] -f [forks] -m [raw]`, best case we end up with a document we can all reference to, worst case you end up with more knowledge than that you started out with.

**Comment by KellerFuchs** [comment]
@DeviaVir Any particular reason for making it a Github wiki thing, rather than having it in https://github.com/hashbang/admin-tools/tree/master/doc ?

**Comment by DeviaVir** [comment]
@KellerFuchs the point you made; I agree we don't need it in our docs per se, but just to give it a visible place I thought GH wiki would be a good place. One of many solutions, though.

**Comment by KellerFuchs** [comment]
@DeviaVir Yes, but having it in the wiki just means we have 2 locations where docs exist and should be looked for and maintained.  I would argue that's strictly worse than having it in `admin-tools/doc`.

My point was that I'm unsure we _should_ document standard Ansible stuff at all, rather than link to [a generic cheat-sheet](http://wall-skills.com/2014/ansible-cheat-sheet/).

**Comment by mayli** [comment]
maybe a link in the wiki points to the real doc in the code?

**Comment by RyanSquared** [comment]
Closing, this is probably common knowledge about Ansible at this point
